name: CI

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Vitest
        run: npx turbo run test --filter=core

      - name: Build
        run: npm run build
